const index = require('express').Router()
const addCompleteCloth = require('./addCompleteCloth')
const getClothes = require('./getClothes')
const id = require('./id')
const checkCartAvailability = require('./checkCartAvailability')
const getCategories = require('./getCategories')
const category = require('./category')
const colorRoute = require('./colorRoute')
const addAbstractCloth = require('./addAbstractCloth')
const addCloth = require('./addCloth')
const deleteCloth = require('./deleteCloth')

index.use('/', addCompleteCloth)
index.use('/', getClothes)
index.use('/', id)
index.use('/', checkCartAvailability)
index.use('/', getCategories)
index.use('/', category)
index.use('/', colorRoute)
index.use('/', addAbstractCloth)
index.use('/', addCloth)
index.use('/', deleteCloth)

module.exports = index
